controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
frontend:
    path: /{angular_route}
    controller: App\Controller\AngularAppController::index
    requirements:
        angular_route: "^(?!api).*$"
